In [1]:
import pandas as pd
import csv
import numpy as np

In [24]:
df = pd.read_csv('bidResCategorizedCP949.csv', encoding='cp949')
df.head(1)

,Unnamed: 0,bidID,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,...,낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(연락처).1,낙찰자(주소),낙찰률,낙찰금액,카테고리,pick_keywords
0,0,1,81,SFL0160,1,47669,***,임시명찰 등 2품목 구매,물품,SFL,...,주식회사 전우밀리터리,Jung woo military,이정구,222730487,02-2273-0487,"경기도 고양시 덕양구 통일로140, 1층 에이143호, 2층 에이261호,지하1층 ...",88.0062,"23,689,950",2종,명찰

In [27]:
df = df.loc[:, ~df.columns.str.contains(r'^Unnamed')]
df

,bidID,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,...,낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(연락처).1,낙찰자(주소),낙찰률,낙찰금액,카테고리,pick_keywords
0,1,81,SFL0160,1,47669,***,임시명찰 등 2품목 구매,물품,SFL,제3283부대,...,주식회사 전우밀리터리,Jung woo military,이정구,222730487,02-2273-0487,"경기도 고양시 덕양구 통일로140, 1층 에이143호, 2층 에이261호,지하1층 ...",88.0062,"23,689,950",2종,명찰
1,2,1,LFC0043,1,45002,1,장거리 이동 신병 도시락 제조납품,물품,LFC,육군훈련소,...,주식회사 엘엔에프 농업회사법인,LNF,이용환,437318109,043-731-8109,충청북도 옥천군 옥천읍 삼청리877-1,96.8333,"5,810",1종,도시락
2,3,22,LGT0034,1,48136,***,0부대 중대시설 분전반 제조설치(16-312),물품,LGT,제2307부대,...,설악테크,seorak tech,김화성,334610399,033-461-0399,강원특별자치도 인제군 북면 원통로74번길10-5(원통농공단지),88.0408,"29,098,720",4종,제조설치
3,4,22,UMM0839,1,48049,***,13-본-국대-01 00학교 가구 및 비품 제조설치,물품,UMM,국군재정관리단,...,주식회사 디에스나이키,"DS NAIKI CO.,LTD",김준홍,27342125,02-734-2125,"서울특별시 구로구 구로중앙로134, 4층(구로동, 리치몰)",88.2297,"2,165,042,000",2종,가구
4,5,9,LGT0035,1,48138,***,00부대 중대시설 조명기구 제조납품(16-314),물품,LGT,제2307부대,...,주식회사 한서,"HANSEO Co.,LTD",이명옥,337462110,033-746-2110,강원특별자치도 원주시 태장공단길47-0 (태장동),88.3713,"32,424,410",4종,조명기구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74727,74728,164,SCQ0154,2,54928,***,수영장자동청소기 등 16종 구매,물품,SCQ,제9911부대,...,대광종합상사,DaKang a general trading company,김정현,336539838,033-653-9838,강원특별자치도 강릉시 경강로2496,89.4840,"25,489,200",2종,청소기
74728,74729,33,HCL0005,1,51,***,24년 간부식당 식자재 구매,물품,HCL,공군사관학교,...,미가온,MIGAON,변정순,319438200,031-943-8200,경기도 파주시 장명산길174-20 (오도동),83.3270,"351,974,920",1종,부식
74729,74730,3,SCR0090,2,61362,***,24년 배추김치(포기절단) 등 10종 구매,물품,SCR,해군제3함대사령부,...,현진식품 영농조합법인,NaN,정재웅,614539877,061-453-9877,전라남도 무안군 망운면 조금나루길22,88.9890,"53,896,000",1종,김치
74730,74731,31,MDS0030,1,66867,***,교육단 증개축 GHP 실외기 설치납품,물품,MDS,제3707부대,...,(주)비케이에너지,BKenergy,이복경,318377674,031-837-7674,경기도 의정부시 민락로387-0 (낙양동),88.0390,"60,496,000",2종,교육
74731,74732,2,SCN0193,1,65508,***,24-체단장 액화석유가스(LPG) 구매,물품,SCN,제7001부대,...,진해산소 일사가스,jinhaeox,노진섭,555465562,055-546-5562,경상남도 창원시 진해구 행암동30-4,88.1870,"20,790,450",3종,가스

In [15]:
df.index = pd.RangeIndex(1,df.shape[0]+1, name='bidID')

In [20]:
df = df.reset_index()
df

,bidID,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,...,낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(연락처).1,낙찰자(주소),낙찰률,낙찰금액,카테고리,pick_keywords
0,1,81,SFL0160,1,47669,***,임시명찰 등 2품목 구매,물품,SFL,제3283부대,...,주식회사 전우밀리터리,Jung woo military,이정구,222730487,02-2273-0487,"경기도 고양시 덕양구 통일로140, 1층 에이143호, 2층 에이261호,지하1층 ...",88.0062,"23,689,950",2종,명찰
1,2,1,LFC0043,1,45002,1,장거리 이동 신병 도시락 제조납품,물품,LFC,육군훈련소,...,주식회사 엘엔에프 농업회사법인,LNF,이용환,437318109,043-731-8109,충청북도 옥천군 옥천읍 삼청리877-1,96.8333,"5,810",1종,도시락
2,3,22,LGT0034,1,48136,***,0부대 중대시설 분전반 제조설치(16-312),물품,LGT,제2307부대,...,설악테크,seorak tech,김화성,334610399,033-461-0399,강원특별자치도 인제군 북면 원통로74번길10-5(원통농공단지),88.0408,"29,098,720",4종,제조설치
3,4,22,UMM0839,1,48049,***,13-본-국대-01 00학교 가구 및 비품 제조설치,물품,UMM,국군재정관리단,...,주식회사 디에스나이키,"DS NAIKI CO.,LTD",김준홍,27342125,02-734-2125,"서울특별시 구로구 구로중앙로134, 4층(구로동, 리치몰)",88.2297,"2,165,042,000",2종,가구
4,5,9,LGT0035,1,48138,***,00부대 중대시설 조명기구 제조납품(16-314),물품,LGT,제2307부대,...,주식회사 한서,"HANSEO Co.,LTD",이명옥,337462110,033-746-2110,강원특별자치도 원주시 태장공단길47-0 (태장동),88.3713,"32,424,410",4종,조명기구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74727,74728,164,SCQ0154,2,54928,***,수영장자동청소기 등 16종 구매,물품,SCQ,제9911부대,...,대광종합상사,DaKang a general trading company,김정현,336539838,033-653-9838,강원특별자치도 강릉시 경강로2496,89.4840,"25,489,200",2종,청소기
74728,74729,33,HCL0005,1,51,***,24년 간부식당 식자재 구매,물품,HCL,공군사관학교,...,미가온,MIGAON,변정순,319438200,031-943-8200,경기도 파주시 장명산길174-20 (오도동),83.3270,"351,974,920",1종,부식
74729,74730,3,SCR0090,2,61362,***,24년 배추김치(포기절단) 등 10종 구매,물품,SCR,해군제3함대사령부,...,현진식품 영농조합법인,NaN,정재웅,614539877,061-453-9877,전라남도 무안군 망운면 조금나루길22,88.9890,"53,896,000",1종,김치
74730,74731,31,MDS0030,1,66867,***,교육단 증개축 GHP 실외기 설치납품,물품,MDS,제3707부대,...,(주)비케이에너지,BKenergy,이복경,318377674,031-837-7674,경기도 의정부시 민락로387-0 (낙양동),88.0390,"60,496,000",2종,교육
74731,74732,2,SCN0193,1,65508,***,24-체단장 액화석유가스(LPG) 구매,물품,SCN,제7001부대,...,진해산소 일사가스,jinhaeox,노진섭,555465562,055-546-5562,경상남도 창원시 진해구 행암동30-4,88.1870,"20,790,450",3종,가스

In [28]:
df.to_csv('bidResCategorizedCP949.csv', index=False, encoding='cp949')

In [29]:
df = pd.read_csv('bidResCategorizedCP949.csv', encoding='cp949')
df

,bidID,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,...,낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(연락처).1,낙찰자(주소),낙찰률,낙찰금액,카테고리,pick_keywords
0,1,81,SFL0160,1,47669,***,임시명찰 등 2품목 구매,물품,SFL,제3283부대,...,주식회사 전우밀리터리,Jung woo military,이정구,222730487,02-2273-0487,"경기도 고양시 덕양구 통일로140, 1층 에이143호, 2층 에이261호,지하1층 ...",88.0062,"23,689,950",2종,명찰
1,2,1,LFC0043,1,45002,1,장거리 이동 신병 도시락 제조납품,물품,LFC,육군훈련소,...,주식회사 엘엔에프 농업회사법인,LNF,이용환,437318109,043-731-8109,충청북도 옥천군 옥천읍 삼청리877-1,96.8333,"5,810",1종,도시락
2,3,22,LGT0034,1,48136,***,0부대 중대시설 분전반 제조설치(16-312),물품,LGT,제2307부대,...,설악테크,seorak tech,김화성,334610399,033-461-0399,강원특별자치도 인제군 북면 원통로74번길10-5(원통농공단지),88.0408,"29,098,720",4종,제조설치
3,4,22,UMM0839,1,48049,***,13-본-국대-01 00학교 가구 및 비품 제조설치,물품,UMM,국군재정관리단,...,주식회사 디에스나이키,"DS NAIKI CO.,LTD",김준홍,27342125,02-734-2125,"서울특별시 구로구 구로중앙로134, 4층(구로동, 리치몰)",88.2297,"2,165,042,000",2종,가구
4,5,9,LGT0035,1,48138,***,00부대 중대시설 조명기구 제조납품(16-314),물품,LGT,제2307부대,...,주식회사 한서,"HANSEO Co.,LTD",이명옥,337462110,033-746-2110,강원특별자치도 원주시 태장공단길47-0 (태장동),88.3713,"32,424,410",4종,조명기구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74727,74728,164,SCQ0154,2,54928,***,수영장자동청소기 등 16종 구매,물품,SCQ,제9911부대,...,대광종합상사,DaKang a general trading company,김정현,336539838,033-653-9838,강원특별자치도 강릉시 경강로2496,89.4840,"25,489,200",2종,청소기
74728,74729,33,HCL0005,1,51,***,24년 간부식당 식자재 구매,물품,HCL,공군사관학교,...,미가온,MIGAON,변정순,319438200,031-943-8200,경기도 파주시 장명산길174-20 (오도동),83.3270,"351,974,920",1종,부식
74729,74730,3,SCR0090,2,61362,***,24년 배추김치(포기절단) 등 10종 구매,물품,SCR,해군제3함대사령부,...,현진식품 영농조합법인,NaN,정재웅,614539877,061-453-9877,전라남도 무안군 망운면 조금나루길22,88.9890,"53,896,000",1종,김치
74730,74731,31,MDS0030,1,66867,***,교육단 증개축 GHP 실외기 설치납품,물품,MDS,제3707부대,...,(주)비케이에너지,BKenergy,이복경,318377674,031-837-7674,경기도 의정부시 민락로387-0 (낙양동),88.0390,"60,496,000",2종,교육
74731,74732,2,SCN0193,1,65508,***,24-체단장 액화석유가스(LPG) 구매,물품,SCN,제7001부대,...,진해산소 일사가스,jinhaeox,노진섭,555465562,055-546-5562,경상남도 창원시 진해구 행암동30-4,88.1870,"20,790,450",3종,가스