# 1. 필요한 데이터만 뽑기

In [82]:
!pip install tqdm

�׼����� �źεǾ����ϴ�.

In [83]:
import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm
import time

## 데이터 불러오기

In [4]:
PBL_df = pd.read_csv("C:/한화에어로스페이스/workspaces/Crawling project/my_projcet/API 수집/API data/Total 물품 낙찰 결과.csv", encoding='cp949')
PBL_df

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(연락처).1,낙찰자(주소),낙찰률,낙찰금액
0,81,SFL0160,1,47669,***,임시명찰 등 2품목 구매,물품,SFL,제3283부대,2016-12-30 12:30,H84F8,주식회사 전우밀리터리,Jung woo military,이정구,222730487,02-2273-0487,"경기도 고양시 덕양구 통일로140, 1층 에이143호, 2층 에이261호,지하1층 ...",88.0062,"23,689,950"
1,1,LFC0043,1,45002,1,장거리 이동 신병 도시락 제조납품,물품,LFC,육군훈련소,2016-12-30 10:00,GA6E7,주식회사 엘엔에프 농업회사법인,LNF,이용환,437318109,043-731-8109,충청북도 옥천군 옥천읍 삼청리877-1,96.8333,"5,810"
2,22,LGT0034,1,48136,***,0부대 중대시설 분전반 제조설치(16-312),물품,LGT,제2307부대,2016-12-29 11:00,F91A4,설악테크,seorak tech,김화성,334610399,033-461-0399,강원특별자치도 인제군 북면 원통로74번길10-5(원통농공단지),88.0408,"29,098,720"
3,22,UMM0839,1,48049,***,13-본-국대-01 00학교 가구 및 비품 제조설치,물품,UMM,국군재정관리단,2016-12-29 11:00,B30CC,주식회사 디에스나이키,"DS NAIKI CO.,LTD",김준홍,27342125,02-734-2125,"서울특별시 구로구 구로중앙로134, 4층(구로동, 리치몰)",88.2297,"2,165,042,000"
4,9,LGT0035,1,48138,***,00부대 중대시설 조명기구 제조납품(16-314),물품,LGT,제2307부대,2016-12-29 11:00,C959B,주식회사 한서,"HANSEO Co.,LTD",이명옥,337462110,033-746-2110,강원특별자치도 원주시 태장공단길47-0 (태장동),88.3713,"32,424,410"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74727,164,SCQ0154,2,54928,***,수영장자동청소기 등 16종 구매,물품,SCQ,제9911부대,2024-01-03 10:30,EF2CA,대광종합상사,DaKang a general trading company,김정현,336539838,033-653-9838,강원특별자치도 강릉시 경강로2496,89.4840,"25,489,200"
74728,33,HCL0005,1,51,***,24년 간부식당 식자재 구매,물품,HCL,공군사관학교,2024-01-03 10:30,D3B5E,미가온,MIGAON,변정순,319438200,031-943-8200,경기도 파주시 장명산길174-20 (오도동),83.3270,"351,974,920"
74729,3,SCR0090,2,61362,***,24년 배추김치(포기절단) 등 10종 구매,물품,SCR,해군제3함대사령부,2024-01-03 10:30,J47CB,현진식품 영농조합법인,NaN,정재웅,614539877,061-453-9877,전라남도 무안군 망운면 조금나루길22,88.9890,"53,896,000"
74730,31,MDS0030,1,66867,***,교육단 증개축 GHP 실외기 설치납품,물품,MDS,제3707부대,2024-01-03 10:30,E1986,(주)비케이에너지,BKenergy,이복경,318377674,031-837-7674,경기도 의정부시 민락로387-0 (낙양동),88.0390,"60,496,000"
74731,2,SCN0193,1,65508,***,24-체단장 액화석유가스(LPG) 구매,물품,SCN,제7001부대,2024-01-02 10:30,G27FF,진해산소 일사가스,jinhaeox,노진섭,555465562,055-546-5562,경상남도 창원시 진해구 행암동30-4,88.1870,"20,790,450"

In [6]:
PBL_df.columns

Index(['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관',
       '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)',
       '낙찰자(연락처).1', '낙찰자(주소)', '낙찰률', ' 낙찰금액 '],
      dtype='object')

### 필요없는 Column 제거

In [7]:
PBL_S_df = PBL_df.drop(['참가수', '공고번호', '공고차수', '항목번호', '입찰명', '업무구분', '발주기관', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)','낙찰자(연락처).1', '낙찰자(주소)', '낙찰률', ' 낙찰금액 '], axis=1)
PBL_S_df.head()

    판단번호 발주기관코드              개찰일시
0  47669    SFL  2016-12-30 12:30
1  45002    LFC  2016-12-30 10:00
2  48136    LGT  2016-12-29 11:00
3  48049    UMM  2016-12-29 11:00
4  48138    LGT  2016-12-29 11:00

#### column명 변경

In [ ]:
rename_dict = {
    '판단번호': 'dcsNo',
    '발주기관코드': 'orntCode',
    '개찰일시': 'demandYear'
}

PBL_S_df = PBL_S_df.rename(columns=rename_dict)

PBL_S_df

       dcsNo orntCode        demandYear
0      47669      SFL  2016-12-30 12:30
1      45002      LFC  2016-12-30 10:00
2      48136      LGT  2016-12-29 11:00
3      48049      UMM  2016-12-29 11:00
4      48138      LGT  2016-12-29 11:00
...      ...      ...               ...
74727  54928      SCQ  2024-01-03 10:30
74728     51      HCL  2024-01-03 10:30
74729  61362      SCR  2024-01-03 10:30
74730  66867      MDS  2024-01-03 10:30
74731  65508      SCN  2024-01-02 10:30

[74732 rows x 3 columns]

#### demandYear에서 '년도'만 남기기

In [65]:
PBL_S_df['demandYear'] = PBL_S_df['demandYear'].astype(str).str[:4]
PBL_S_df.head(8)

   dcsNo orntCode demandYear
0  47669      SFL       2016
1  45002      LFC       2016
2  48136      LGT       2016
3  48049      UMM       2016
4  48138      LGT       2016
5  48057      HCL       2016
6  49073      LNF       2016
7     19      HCM       2016

In [77]:
#국내 조달계획 상세 

base_url = 'http://openapi.d2b.go.kr/openapi/service/PrcurePlanInfoService/'
service_name = 'getDmstcPrcurePlanDetail'
serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
demandYear  = '2021'        #요구년도
orntCode    = 'SFG'         #발주기관코드
dcsNo=	    '4554'         #판단번호

params = f'serviceKey={serviceKey}&demandYear={demandYear}&orntCode={orntCode}&dcsNo={dcsNo}'

url = f'{base_url}{service_name}?{params}'
url

'http://openapi.d2b.go.kr/openapi/service/PrcurePlanInfoService/getDmstcPrcurePlanDetail?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2021&orntCode=SFG&dcsNo=4554'

In [ ]:
base_url = 'http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/'
service_name = 'getDmstcCmpetBidPblancItem'
serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'

result_list = []
fail_list = [] 

for index, row in PBL_S_df.iterrows():
    demandYear = row['demandYear']
    orntCode = row['orntCode']
    dcsNo = row['dcsNo']

    params = f'serviceKey={serviceKey}&demandYear={demandYear}&orntCode={orntCode}&dcsNo={dcsNo}'
    url = f'{base_url}{service_name}?{params}'
    
    print(f"{index+1}번째 행 호출 중... URL: {url}")

    try:
        response = requests.get(url, timeout=5)
        soup = BeautifulSoup(response.content, 'xml')
        
        item = soup.find('item')
        if item:
            data_dict = {tag.name: tag.text for tag in item.find_all()}
            fail_list.append(data_dict)
        else:
            print(f"  -> {index+1}번째 행({dcsNo})에서 데이터를 찾지 못했습니다.")
            no_data_info = {
                'demandYear': demandYear,
                'orntCode': orntCode,
                'dcsNo': dcsNo
            }
            fail_list.append(no_data_info)

    except Exception as e:
        print(f"  -> {index+1}번째 행({dcsNo})에서 오류 발생: {e}")

result_df = pd.DataFrame(result_list)
Nodata_df = pd.DataFrame(fail_list)

# 최종 결과 확인
print("\n--- ✅ API 호출 성공 데이터프레임 ---")
print(result_df)

print("\n--- ❌ 데이터를 찾지 못한 목록 ---")
print(Nodata_df)

1번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFL&dcsNo=47669
2번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LFC&dcsNo=45002
3번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LGT&dcsNo=48136
4번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=UMM&dcsNo=48049
5번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LGT&dcsNo=48138
6번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=HCL&dcsNo=48057
7번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LNF&dcsNo=49073
8번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=HCM&dcsNo=19
  -> 8번째 행(19)에서 데이터를 찾지 못했습니다.
9번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=HCL&dcsNo=46235
10번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFC&dcsNo=47835
11번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFC&dcsNo=47822
12번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFC&dcsNo=47817
13번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LPG&dcsNo=48186
14번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=EGD&dcsNo=6003
15번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=HCS&dcsNo=45437
16번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDR&dcsNo=47084
17번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFH&dcsNo=46951
18번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDI&dcsNo=45104
19번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDG&dcsNo=46660
20번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDG&dcsNo=46659
21번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDG&dcsNo=46658
22번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFH&dcsNo=46951
23번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDI&dcsNo=45104
24번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDG&dcsNo=46660
25번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDG&dcsNo=46659
26번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDG&dcsNo=46658
27번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MCN&dcsNo=47177
28번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MCN&dcsNo=45582
29번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MCN&dcsNo=45577
30번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LNR&dcsNo=47500
31번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LHK&dcsNo=43261
32번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LHD&dcsNo=46286
33번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LGP&dcsNo=46983
34번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LCH&dcsNo=46198
35번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LCF&dcsNo=43703
36번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LHN&dcsNo=48112
37번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFM&dcsNo=47257
38번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFM&dcsNo=47201
39번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFM&dcsNo=47192
40번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFM&dcsNo=47189
41번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFC&dcsNo=47454
42번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SCR&dcsNo=46684
43번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SCF&dcsNo=44767
44번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDJ&dcsNo=46562
45번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LFN&dcsNo=46470
46번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=HCR&dcsNo=41943
47번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFH&dcsNo=46635
48번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDD&dcsNo=46308
49번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDD&dcsNo=46307
50번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFG&dcsNo=47665
51번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=HDP&dcsNo=44994
52번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=UAC&dcsNo=46754
53번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=UAC&dcsNo=43976
54번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LPG&dcsNo=47516
55번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDR&dcsNo=47087
56번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LMS&dcsNo=45083
57번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LDC&dcsNo=46485
58번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MCN&dcsNo=44287
59번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LNT&dcsNo=46214
60번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LNF&dcsNo=47273
61번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LHN&dcsNo=46759
62번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LHN&dcsNo=46739
63번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LHN&dcsNo=46716
64번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LHN&dcsNo=46712
65번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=UAZ&dcsNo=46609
66번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=HCL&dcsNo=46557
67번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SCF&dcsNo=45696
68번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=HDR&dcsNo=46233
69번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MCN&dcsNo=45953
70번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MCN&dcsNo=45951
71번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MCN&dcsNo=45948
72번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MCN&dcsNo=45935
73번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MCN&dcsNo=45834
74번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LCH&dcsNo=46213
75번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LCH&dcsNo=46262
76번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LNG&dcsNo=46283
77번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LKP&dcsNo=45910
78번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LCF&dcsNo=46358
79번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDG&dcsNo=44367
80번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDG&dcsNo=44367
81번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=UMM&dcsNo=41658
82번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDG&dcsNo=44367
83번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MDF&dcsNo=45939
84번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=MCJ&dcsNo=45088
85번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=HCF&dcsNo=45072
86번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LPM&dcsNo=46745
87번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=LNF&dcsNo=46699
88번째 행 호출 중... URL: http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/getDmstcCmpetBidPblancItem?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&demandYear=2016&orntCode=SFG&dcsNo=45148

KeyboardInterrupt:

In [85]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from tqdm import tqdm
import time

base_url = 'http://openapi.d2b.go.kr/openapi/service/BidPblancInfoService/'
service_name = 'getDmstcCmpetBidPblancItem'
serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'

result_list = []
Nodata_list = []

# 'demandYear'가 2016인 데이터만 필터링
pbl_2016_df = PBL_S_df[PBL_S_df['demandYear'] == '2016'].copy()
print(f"✅ 2016년 데이터 {len(pbl_2016_df)}건을 대상으로 테스트를 시작합니다.")

# tqdm 진행률 바 객체를 변수에 저장합니다.
progress_bar = tqdm(pbl_2016_df.iterrows(), total=len(pbl_2016_df), desc="2016년 데이터 호출 중")

# for 루프에서 이 객체를 사용합니다.
for index, row in progress_bar:
    demandYear = row['demandYear']
    orntCode = row['orntCode']
    dcsNo = row['dcsNo']

    params = f'serviceKey={serviceKey}&demandYear={demandYear}&orntCode={orntCode}&dcsNo={dcsNo}'
    url = f'{base_url}{service_name}?{params}'

    try:
        response = requests.get(url, timeout=5)
        soup = BeautifulSoup(response.content, 'xml')
        
        item = soup.find('item')
        if item:
            data_dict = {tag.name: tag.text for tag in item.find_all()}
            result_list.append(data_dict)
        else:
            no_data_info = {'demandYear': demandYear, 'orntCode': orntCode, 'dcsNo': dcsNo}
            Nodata_list.append(no_data_info)

    except Exception as e:
        error_info = {'demandYear': demandYear, 'orntCode': orntCode, 'dcsNo': f"Error: {e}"}
        Nodata_list.append(error_info)
    
    # --- 이 부분이 변경되었습니다 ---
    # 진행률 바의 오른쪽에 표시될 텍스트를 실시간으로 업데이트합니다.
    progress_bar.set_postfix(성공=len(result_list), 실패=len(Nodata_list))
    # -----------------------------

# 모든 결과를 각각의 데이터프레임으로 변환
result_df = pd.DataFrame(result_list)
Nodata_df = pd.DataFrame(Nodata_list)

# 최종 결과 확인
print("\n" + "="*50)
print("\n--- ✅ API 호출 성공 데이터프레임 (2016년) ---")
print(result_df)

print("\n--- ❌ 데이터를 찾지 못한 목록 (2016년) ---")
print(Nodata_df)

✅ 2016년 데이터 9004건을 대상으로 테스트를 시작합니다.

2016년 데이터 호출 중:   0%|          | 0/9004 [00:00<?, ?it/s]

2016년 데이터 호출 중: 100%|██████████| 9004/9004 [11:48<00:00, 12.70it/s, 성공=6622, 실패=2382]

==================================================

--- ✅ API 호출 성공 데이터프레임 (2016년) ---
      apeqCode       apeqName aprvDate bugtDivs codeVld1 codeVld2  \
0                                            U0
1                                            U0
2                                            A1
3                                            A1
4                                            A1
...        ...            ...      ...      ...      ...      ...
6617                                         12  물품구매요구서       본조
6618  43310102            압축기                12                본조
6619  65100104  세탁장치,트레일러 탑재식                12    국방/정식       본조
6620                        -                1A  물품구매요구서     장기국채
6621                                         12    국방/현품       본조

         codeVld3 codeVld4  dlvrDate dlvrPrrk  ...       niin    ordrUtpr  \
0           소요군검수       해군  20161222      001  ...  000000001    27754000
1           소요군검사       육군  20171231      001  ...  A00000000        6000
2           소요군검사       육군  20161223      001  ...  N00000000    33495000
3           소요군검사       국직  20170531      001  ...  000000000  2492346210
4           소요군검사       육군  20161224      001  ...  N00000000    37132000
...           ...      ...       ...      ...  ...        ...         ...
6617  표준품질보증형(Ⅲ형)       육군  20160630      001  ...  37X120036       25278
6618  표준품질보증형(Ⅲ형)       해군  20161028      001  ...  375045412       56645
6619  표준품질보증형(Ⅲ형)       육군  20161223      001  ...  375131866    57319500
6620  단순품질보증형(I형)       육군  20160401      001  ...  37X152436         597
6621  표준품질보증형(Ⅲ형)       육군  20160330      001  ...  375083060      790000

                         partNumb         prcmRnum refcNumb specClas  \
0                                  MP201646182A001
1                                  MB201643687A001
2                                  MB201646653A001
3                                  TM201646547A001
4                                  MB201646655A001
...                           ...              ...      ...      ...
6617                                MBDLSO16200017                 U
6618                000 N92 034/1   MPDPLA16201234
6619  ADTW30A001, TW30A, TW30A001   MBDLMI16270004                 B
6620                                MBDLSP16A00187                 U
6621                    T42000002   MBDBE161050061                 S

       specNumb stnbTycd    totlAmnt unit
0                           27754000   YE
1                          192732000   YE
2                           33495000   YE
3        내역서 참조           2492346210   YE
4                           37132000   YE
...         ...      ...         ...  ...
6617                       758340000   KT
6618  N91003601              3625280   EA
6619  3510-4001           1146390000   EA
6620                        24268050   EA
6621  1550-3004             24490000   EA

[6622 rows x 26 columns]

--- ❌ 데이터를 찾지 못한 목록 (2016년) ---
     demandYear orntCode  dcsNo
0          2016      HCM     19
1          2016      EGF     22
2          2016      EGH    549
3          2016      EGH    534
4          2016      EGG     70
...         ...      ...    ...
2377       2016      MDJ  43186
2378       2016      SFG  46163
2379       2016      SFG  46164
2380       2016      LMD  46063
2381       2016      SFG  45778

[2382 rows x 3 columns]

In [87]:
result_df

,apeqCode,apeqName,aprvDate,bugtDivs,codeVld1,codeVld2,codeVld3,codeVld4,dlvrDate,dlvrPrrk,...,niin,ordrUtpr,partNumb,prcmRnum,refcNumb,specClas,specNumb,stnbTycd,totlAmnt,unit
0,,,,U0,,,소요군검수,해군,20161222,001,...,000000001,27754000,,MP201646182A001,,,,,27754000,YE
1,,,,U0,,,소요군검사,육군,20171231,001,...,A00000000,6000,,MB201643687A001,,,,,192732000,YE
2,,,,A1,,,소요군검사,육군,20161223,001,...,N00000000,33495000,,MB201646653A001,,,,,33495000,YE
3,,,,A1,,,소요군검사,국직,20170531,001,...,000000000,2492346210,,TM201646547A001,,,내역서 참조,,2492346210,YE
4,,,,A1,,,소요군검사,육군,20161224,001,...,N00000000,37132000,,MB201646655A001,,,,,37132000,YE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6617,,,,12,물품구매요구서,본조,표준품질보증형(Ⅲ형),육군,20160630,001,...,37X120036,25278,,MBDLSO16200017,,U,,,758340000,KT
6618,43310102,압축기,,12,,본조,표준품질보증형(Ⅲ형),해군,20161028,001,...,375045412,56645,000 N92 034/1,MPDPLA16201234,,,N91003601,,3625280,EA
6619,65100104,"세탁장치,트레일러 탑재식",,12,국방/정식,본조,표준품질보증형(Ⅲ형),육군,20161223,001,...,375131866,57319500,"ADTW30A001, TW30A, TW30A001",MBDLMI16270004,,B,3510-4001,,1146390000,EA
6620,,-,,1A,물품구매요구서,장기국채,단순품질보증형(I형),육군,20160401,001,...,37X152436,597,,MBDLSP16A00187,,U,,,24268050,EA
6621,,,,12,국방/현품,본조,표준품질보증형(Ⅲ형),육군,20160330,001,...,375083060,790000,T42000002,MBDBE161050061,,S,1550-3004,,24490000,EA

In [ ]:
tag_names = ['apeqCode', 'apeqName', 'aprvDate', 'bugtDivs', 'codeVld1', 'codeVld2',
       'codeVld3', 'codeVld4', 'dlvrDate', 'dlvrPrrk', 'dlvrQnty', 'dlvrRegn',
       'dmstItnb', 'fsc', 'itemName', 'miltDivs', 'niin', 'ordrUtpr',
       'partNumb', 'prcmRnum', 'refcNumb', 'specClas', 'specNumb', 'stnbTycd',
       'totlAmnt', 'unit']
col_names = ['항목번호','조달요구번호','군급','국가품목식별번호','재고번호형태부호','품명','적용장비','규격번호','규격종류','규격종류명','부품번호','참조번호','예산구분코드','예산구분명','단위','단가','납지','납기','수량','납지순위','품보형태','적용장비','군구분','군부분명','승인일자','금액','페이지당항목수']
list(zip(tag_names, col_names))

In [94]:
result_df.columns

Index(['적용장비', '적용장비', '승인일자', '예산구분코드', '규격종류명', '예산구분명', '품보형태', '군부분명',
       '납기', '납지순위', '수량', '납지', '항목번호', '군급', '품명', '군구분', '국가품목식별번호', '단가',
       '부품번호', '조달요구번호', '참조번호', '규격종류', '규격번호', '재고번호형태부호', '금액', '단위'],
      dtype='object')

In [100]:
#국내조달 상세
column_mapping = {
    'resultCode': '결과코드',
    'resultMag': '결과메시지',
    'dmstItnb': '항목번호',
    'prcmRnum': '조달요구번호',
    'fsc': '군급',
    'niin': '국가품목식별번호',
    'stnbTycd': '재고번호형태부호',
    'itemName': '품명',
    'apeqName': '적용장비',
    'specNumb': '규격번호',
    'specClas': '규격종류',
    'codeVld1': '규격종류명',
    'partNumb': '부품번호',
    'refcNumb': '참조번호',
    'bugtDivs': '예산구분코드',
    'codeVld2': '예산구분명',
    'unit': '단위',
    'ordrUtpr': '단가',
    'dlvrRegn': '납지',
    'dlvrDate': '납기',
    'dlvrQnty': '수량',
    'dlvrPrrk': '납지순위',
    'codeVld3': '품보형태',
    'apeqCode': '적용장비',
    'miltDivs': '군구분',
    'codeVld4': '군부분명',
    'aprvDate': '승인일자',
    'totlAmnt': '금액',
    'numOfRows': '페이지당항목수'
}

# rename 함수를 사용하여 컬럼명을 변경하고, 결과를 다시 result_df에 저장합니다.
result_df = result_df.rename(columns=column_mapping)

# 변경된 컬럼명과 데이터프레임의 상위 5개 행을 확인합니다.
print("--- 변경 후 컬럼명 ---")
print(result_df.columns)

print("\n--- 변경된 데이터프레임 ---")
result_df

--- 변경 후 컬럼명 ---
Index(['품명'], dtype='object')

--- 변경된 데이터프레임 ---

                 품명
0        임시명찰 등 2품목
1               도시락
2               분전반
3          가구 및 비품류
4              조명기구
...             ...
6617      전투용응급처치키트
6618      밸브,안전릴리프형
6619  세탁장치,트레일러 탑재식
6620   태극기(일반색),벨크로
6621      대공 표적기,소형

[6622 rows x 1 columns]

In [ ]:
# file_name = '2016_명세서.csv'
# result_df.to_csv(file_name, index=False, encoding='cp949')

<!-- #국내조달 상세
column_mapping = {
'demandYear' : '요구년도'   
'orntCode' : '발주기관코드'
'ornt' : '발주기관'
'dcsNo' : '판단번호'
'excutPrearngeMt' : '집행예정월'
'cntrctPrearngeMt' : '계약예정월'
'reprsntPrdlstNm' : '대표품목명'
'qy' : '수량'
'excutTy' : '집행유형'
'orgnlbudgtAmount' : '본조금액'
'ntndbtAmount' : '국채금액'
'unDcsnAmount' : '미확정금액'
'budgetSmAmount' : '예산합계금액'
'totBukipAmount' : '총부기금액'
'cntrctMth' : '계약방법'
'prvcntrResn' : '수의계약사유'
'bidMth' : '입찰방법'
'untpcSystemTy' : '단가제도유형'
'cntrctKnd' : '계약종류'
'sucbidrDecsnMth' : '낙찰자결정방법'
'bidStle' : '입찰형태'
'gnrlzDcs'  : '종합판단'
'prdlstCode' : '품목코드'
'prdlstNm' : '품목명'
'industClList' : '산업분류목록'
'chargerNm' : '담당자명'
'chargerCttpc' : '담당자연락처'
'bidPrearngeDate' : '입찰예정일자'
}'

# rename 함수를 사용하여 컬럼명을 변경하고, 결과를 다시 result_df에 저장합니다.
result_df = result_df.rename(columns=column_mapping)

# 변경된 컬럼명과 데이터프레임의 상위 5개 행을 확인합니다.
print("--- 변경 후 컬럼명 ---")
print(result_df.columns)

print("\n--- 변경된 데이터프레임 ---")
result_df -->

In [44]:
file_name = '명세서 테스트.csv'
result_df.to_csv(file_name, index=False, encoding='cp949')

In [ ]:
result_T_df = result_df.drop(['적용장비', '적용장비', '승인일자', '예산구분코드', '규격종류명', '예산구분명', '품보형태', '군부분명',
       '납기', '납지순위', '수량', '납지', '항목번호', '군급', '군구분', '국가품목식별번호', '단가',
       '부품번호', '조달요구번호', '참조번호', '규격종류', '규격번호', '재고번호형태부호', '금액', '단위'], axis=1)
result_T_df.head()

KeyError: "['적용장비', '적용장비', '승인일자', '예산구분코드', '규격종류명', '예산구분명', '품보형태', '군부분명', '납기', '납지순위', '수량', '납지', '항목번호', '군급', '군구분', '국가품목식별번호', '단가', '부품번호', '조달요구번호', '참조번호', '규격종류', '규격번호', '재고번호형태부호', '금액', '단위'] not found in axis"

In [114]:
result_T_df.to_csv('품목명_read.csv', index=False, encoding='UTF-8')

In [108]:
import pandas as pd

# 1. CSV 파일 읽기
try:
    df = pd.read_csv('품목명.csv', encoding='cp949')
    # CSV 파일에 '품명'이라는 컬럼이 있는지 확인
    if '품명' not in df.columns:
        print("오류: '품목명.csv' 파일에 '품명' 컬럼이 존재하지 않습니다.")
        # 만약 컬럼명이 다르다면, 여기서 df.rename() 등을 사용하여 '품명'으로 변경해야 합니다.
        exit()
except FileNotFoundError:
    print("오류: '품목명.csv' 파일을 찾을 수 없습니다. 파일이 현재 위치에 있는지 확인해주세요.")
    exit()

# 2. 분류 기준 정의 (키워드 기반)
# 각 종별로 대표적인 키워드를 리스트 형태로 정의합니다. 우선순위가 높은 것을 먼저 배치합니다.
classification_keywords = {
    '5종 탄약류': ['수류탄', '탄약', '지뢰', '폭약', '신관', '포탄', '유도탄'],
    '7종 장비류': ['헬기', '레이더', '무기', '장비', '전차', '장갑차', 'CCTV', '크레인', '탐지기', '보일러', '냉난방기', '작업차'],
    '9종 수리부속·공구류': ['수리부속', '공구', '정비', '조립체', '오-링', '연결축', '기어'],
    '8종 의무 장비·물자': ['의무', '의약품'],
    '3종 유류': ['유류', 'LPG', '가스', '경유', '휘발유', '등유', '윤활유', '냉매', '연료'],
    '4. 종 건설자재': ['목재', '철근', '시멘트', '페인트', '철조망', '철책', '패널', '자재'],
    '1종 식량류': ['식량', '양념', '소스', '식초', '우유', '주스', '김치', '두부', '쌀국수', '시리얼', '돈까스', '소시지', '햄', '빵', '떡', '탕', '전분', '초코파이', '분식', '면류', '건빵'],
    '2종 일반물자류': ['명찰', '도시락', '분전반', '가구', '비품', '조명', '피복', '침구', '장구', '기재', '기구', '전지', '무전기', '전산', '소화기', '지도', '반합', '책상', '펜', '배터리'],
    '6종 복지매장 판매품(PX 물품)': ['PX'] # PX는 키워드가 명확하지 않아, 식품류/일반물자류와 겹치는 경우가 많습니다.
}

# 3. 품목명을 분류하는 함수 정의
def classify_item(item_name):
    """품목명을 입력받아 해당하는 군수품 종별을 반환하는 함수"""
    # item_name이 문자열이 아닐 경우를 대비
    if not isinstance(item_name, str):
        return '10종 기타'
    
    # 정의된 키워드 딕셔너리를 순회하며 검사
    for category, keywords in classification_keywords.items():
        for keyword in keywords:
            if keyword in item_name:
                return category # 키워드가 발견되면 해당 종별을 반환
    
    # 모든 키워드에 해당하지 않으면 '10종 기타'로 분류
    return '10종 기타'

# 4. '품명' 컬럼에 분류 함수를 적용하여 '분류' 컬럼 생성
df['분류'] = df['품명'].apply(classify_item)

# 5. 결과 확인
df

                 품명        분류
0        임시명찰 등 2품목  2종 일반물자류
1               도시락  2종 일반물자류
2               분전반  2종 일반물자류
3          가구 및 비품류  2종 일반물자류
4              조명기구  2종 일반물자류
...             ...       ...
6617      전투용응급처치키트    10종 기타
6618      밸브,안전릴리프형    10종 기타
6619  세탁장치,트레일러 탑재식    10종 기타
6620   태극기(일반색),벨크로    10종 기타
6621      대공 표적기,소형    10종 기타

[6622 rows x 2 columns]

In [109]:
df.to_csv('2016_물품분류.csv',  index=False, encoding='cp949')